// frontend/src/pages/Register.jsx
import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { registerUser } from '../services/api';

const Register = () => {
    const [form, setForm] = useState({ name: '', email: '', password: '', role: 'admin' });
    const [error, setError] = useState('');
    const [success, setSuccess] = useState('');
    const [loading, setLoading] = useState(false);
    const navigate = useNavigate();

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');
        setLoading(true);
        try {
            await registerUser(form);
            setSuccess('Account created! Redirecting to login...');
            setTimeout(() => navigate('/login'), 2000);
        } catch (err) {
            setError(err.response?.data?.message || 'Registration failed');
        } finally { setLoading(false); }
    };

    return (
        <div className="min-vh-100 d-flex align-items-center justify-content-center"
            style={{ background: 'linear-gradient(135deg,#1a1a2e 0%,#16213e 50%,#0f3460 100%)' }}>
            <div className="col-md-5">
                <div className="card shadow-lg border-0" style={{ borderRadius: '20px' }}>
                    <div className="card-header text-white text-center py-4 border-0"
                        style={{ background: 'linear-gradient(135deg,#667eea,#764ba2)', borderRadius: '20px 20px 0 0' }}>
                        <i className="bi bi-person-plus-fill" style={{ fontSize: '2.5rem' }}></i>
                        <h3 className="fw-bold mt-2 mb-0">Create Account</h3>
                    </div>
                    <div className="card-body p-4">
                        {error && <div className="alert alert-danger small">{error}</div>}
                        {success && <div className="alert alert-success small">{success}</div>}
                        <form onSubmit={handleSubmit}>
                            <div className="mb-3">
                                <label className="form-label fw-semibold small text-secondary">Full Name</label>
                                <input type="text" className="form-control" placeholder="Your full name"
                                    value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required />
                            </div>
                            <div className="mb-3">
                                <label className="form-label fw-semibold small text-secondary">Email</label>
                                <input type="email" className="form-control" placeholder="your@email.com"
                                    value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required />
                            </div>
                            <div className="mb-3">
                                <label className="form-label fw-semibold small text-secondary">Password</label>
                                <input type="password" className="form-control" placeholder="Min 6 characters"
                                    value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} required />
                            </div>
                            <div className="mb-4">
                                <label className="form-label fw-semibold small text-secondary">Role</label>
                                <select className="form-select" value={form.role}
                                    onChange={e => setForm({ ...form, role: e.target.value })}>
                                    <option value="admin">Admin</option>
                                    <option value="faculty">Faculty</option>
                                    <option value="student">Student</option>
                                </select>
                            </div>
                            <button type="submit" className="btn w-100 py-2 text-white fw-semibold"
                                disabled={loading}
                                style={{ background: 'linear-gradient(135deg,#667eea,#764ba2)', border: 'none', borderRadius: '10px' }}>
                                {loading ? <><span className="spinner-border spinner-border-sm me-2" />Creating...</> : 'Create Account'}
                            </button>
                        </form>
                    </div>
                    <div className="card-footer text-center bg-light py-3 border-0">
                        <small>Already have an account? <Link to="/login" className="fw-semibold" style={{ color: '#667eea' }}>Sign In</Link></small>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Register;

// angular-app/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
    selector: 'app-register',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './register.component.html',
    styleUrls: ['./register.component.css']
})
export class RegisterComponent {

    form = {
        name: '',
        email: '',
        password: '',
        role: 'admin'
    };

    error = '';
    success = '';
    loading = false;

    // Relative path — Angular dev proxy forwards /api/* → http://localhost:5000/api
    private apiBase = '/api';

    constructor(private http: HttpClient) { }

    handleSubmit(event: Event) {
        event.preventDefault();
        this.error = '';
        this.success = '';
        this.loading = true;

        this.http.post(`${this.apiBase}/auth/register`, this.form).subscribe({
            next: () => {
                this.loading = false;
                this.success = 'Account created! Redirecting to login...';
                setTimeout(() => {
                    window.location.href = 'http://localhost:3000/login';
                }, 2000);
            },
            error: (err) => {
                this.loading = false;
                console.error('Register error:', err);
                const msg = err?.error?.message
                    || err?.message
                    || `Registration failed (status: ${err?.status ?? 'network error'})`;
                this.error = msg;
            }
        });
    }

    goToLogin() {
        window.location.href = 'http://localhost:3000/login';
    }
}

<div class="register-wrapper">
    <div class="register-card-container">
        <div class="register-card">

            <!-- Header -->
            <div class="card-header">
                <div class="icon-wrap">
                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="white" viewBox="0 0 16 16">
                        <path
                            d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                        <path fill-rule="evenodd"
                            d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
                    </svg>
                </div>
                <h3>Create Account</h3>
            </div>

            <!-- Body -->
            <div class="card-body">
                <!-- Error Alert -->
                <div class="alert alert-danger" *ngIf="error">{{ error }}</div>

                <!-- Success Alert -->
                <div class="alert alert-success" *ngIf="success">{{ success }}</div>

                <form (ngSubmit)="handleSubmit($event)">
                    <!-- Full Name -->
                    <div class="form-group">
                        <label class="form-label">Full Name</label>
                        <input type="text" class="form-control" placeholder="Your full name" [(ngModel)]="form.name"
                            name="name" required />
                    </div>

                    <!-- Email -->
                    <div class="form-group">
                        <label class="form-label">Email</label>
                        <input type="email" class="form-control" placeholder="your@email.com" [(ngModel)]="form.email"
                            name="email" required />
                    </div>

                    <!-- Password -->
                    <div class="form-group">
                        <label class="form-label">Password</label>
                        <input type="password" class="form-control" placeholder="Min 6 characters"
                            [(ngModel)]="form.password" name="password" required />
                    </div>

                    <!-- Role -->
                    <div class="form-group mb-extra">
                        <label class="form-label">Role</label>
                        <select class="form-control form-select" [(ngModel)]="form.role" name="role">
                            <option value="admin">Admin</option>
                            <option value="faculty">Faculty</option>
                            <option value="student">Student</option>
                        </select>
                    </div>

                    <!-- Submit Button -->
                    <button type="submit" class="btn-submit" [disabled]="loading">
                        <span *ngIf="loading" class="spinner"></span>
                        <span>{{ loading ? 'Creating...' : 'Create Account' }}</span>
                    </button>
                </form>
            </div>

            <!-- Footer -->
            <div class="card-footer">
                <small>
                    Already have an account?
                    <a (click)="goToLogin()" class="signin-link">Sign In</a>
                </small>
            </div>

        </div>
    </div>
</div>
